FROM node:20-alpine AS frontend-builder

WORKDIR /app

# Копируем package.json из папки frontend
COPY frontend/package*.json ./
RUN npm install

# Копируем весь исходный код фронтенда
COPY frontend/ .

RUN npm run build


# --- Этап 2: Финальный образ Nginx ---
FROM nginx:1.25-alpine

# Копируем кастомную конфигурацию Nginx
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Копируем собранные статические файлы из этапа 'frontend-builder'
COPY --from=frontend-builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]```